sudo: false  # Container Based
language: node_js
node_js:
  - "7"
  - "node"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.8

install:
  - npm install

script:
  - ./travis_test.sh

deploy:
  provider: heroku
  api_key:
    secure: aSCy+1wGbLLWS0JxazizKmKk5zhMQuxRTvYtXCfa5rbyhWu2uuC73QG4kcTYEWy51tdp4Au0o0UfF51VJiD4C6XARPXWhbiMsqLv5yj2bJDsbQWJX6p5hvJXHG4yZxwY8J2NHFTH/psA1fp55lFw1CR0A5fp5gJIBJPXDzA2qm4=
  app: gochiusa-bot
  on: production
